# Generated by Django 3.0.7 on 2020-07-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200703_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='take_on_event',
            field=models.BooleanField(default=False),
        ),
    ]
