# Generated by Django 3.0.7 on 2020-07-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200703_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start',
        ),
    ]
