# Generated by Django 3.0.7 on 2020-06-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_charge_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='charge_num',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
