# Generated by Django 3.0.7 on 2020-06-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_charge_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='charge_num',
            field=models.IntegerField(default=0),
        ),
    ]
