# Generated by Django 3.0.7 on 2020-07-05 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='charge_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='in_charge_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
