# Generated by Django 3.0.7 on 2020-06-21 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200621_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='charge_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
