# Generated by Django 3.0.7 on 2020-06-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmanger',
            options={'permissions': [('can_add', 'can add users to group'), ('can_delete', 'can delete users from group')]},
        ),
    ]
