# Generated by Django 3.0.7 on 2020-06-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200625_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmanger',
            options={},
        ),
    ]
