# Generated by Django 3.0.7 on 2020-06-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_groupusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupusers',
            name='events',
        ),
        migrations.RemoveField(
            model_name='groupusers',
            name='group',
        ),
        migrations.DeleteModel(
            name='GroupManger',
        ),
        migrations.DeleteModel(
            name='GroupUsers',
        ),
    ]
