# Generated by Django 3.0.7 on 2020-06-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_friendrequest_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='created',
        ),
    ]
